services:
  - type: web
    name: fin-tech
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/java/openjdk