spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:3306/railway
    username: root
    password: ToZIiCRrZaDYNANBXQbOpoUIJQscsbCr
server:
  port: 8080

app:
  verify-host: http://localhost:8080
  ui-app-url: http://localhost:5173
  jwt:
    secret: eU7Gvpt6X2P9fEJvV+0wz1oRj9tcgQ5BdMniA8xYgls=
    access-token-expiration-ms: 3600000
