spring:
  application:
    name: fin-tech
  profiles:
    active: dev
  datasource:
    # URL'i tırnak içine almak, özel karakterlerden kaynaklanabilecek sorunları önler.
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ve Hibernate ayarları
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

# Uygulamaya özel (custom) ayarlar
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${EXPIRATION_DURATION:PT1H}

# Sunucu ayarları
server:
  port: ${PORT:8080}

